<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_sbic vYOkbe</name>
   <tag></tag>
   <elementGuidId>8879fd12-76af-42e1-a78e-398a3d265a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Alh6id']/div/div/ul/li/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sbic.vYOkbe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf16eef9-d361-4eca-ba7e-bef04f012817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sbic vYOkbe</value>
      <webElementGuid>eadf82c3-dc31-47ee-9a8f-9530e298740e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Hn9OVkTFOAKfltgZHPfrmnyZ8ObXu4UpINft0Uc&amp;s=10</value>
      <webElementGuid>755a659c-f418-43e6-bb10-87dec8adbe15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Alh6id&quot;)/div[@class=&quot;erkvQe&quot;]/div[@class=&quot;OBMEnb&quot;]/ul[@class=&quot;G43f7e&quot;]/li[@class=&quot;sbct PZPZlf sbre sbhl&quot;]/div[@class=&quot;eIPGRd&quot;]/div[@class=&quot;sbic vYOkbe&quot;]</value>
      <webElementGuid>3e14ed78-a20f-4874-9009-6712b50d9c30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Alh6id']/div/div/ul/li/div/div</value>
      <webElementGuid>fc208b15-6dae-4ef2-a3e8-3ac86300348f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>c04a13c8-a641-4ebd-87fd-c0a24422fcaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
